# Generated by Django 5.2.6 on 2025-11-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='tipo',
            field=models.CharField(choices=[('AC', 'Ar-Condicionado'), ('LUZ', 'Luz')], default='LUZ', max_length=3, verbose_name='Tipo de Sensor'),
        ),
        migrations.DeleteModel(
            name='TipoSensor',
        ),
    ]
