# Generated by Django 5.2.6 on 2025-10-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArCondicionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ligado', models.BooleanField(default=False)),
                ('temperatura', models.IntegerField(default=24)),
                ('modo', models.CharField(default='Frio', max_length=20)),
                ('velocidade', models.CharField(default='Média', max_length=10)),
            ],
        ),
    ]
