# Generated by Django 5.2.6 on 2025-10-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_condicionado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcondicionado',
            name='inicio_ligado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
